;########### SECCION DE DATOS
section .data

;########### SECCION DE TEXTO (PROGRAMA)
section .text

; Completar las definiciones (serán revisadas por ABI enforcer):
USUARIO_ID_OFFSET EQU 0 ;[0, 4) 
USUARIO_NIVEL_OFFSET EQU 4;[4, 8)
USUARIO_SIZE EQU 8

CASO_CATEGORIA_OFFSET EQU 0 ;[0, 4)
CASO_ESTADO_OFFSET EQU 4 ;[4, 7)
CASO_USUARIO_OFFSET EQU 8 ;padding 1 xq 7 no es multiplo de 8. [8, 16)
CASO_SIZE EQU 16

SEGMENTACION_CASOS0_OFFSET EQU 0 ; [0, 8)
SEGMENTACION_CASOS1_OFFSET EQU 8 ;[8, 16)
SEGMENTACION_CASOS2_OFFSET EQU 16 ;[16, 24)
SEGMENTACION_SIZE EQU 24

ESTADISTICAS_CLT_OFFSET EQU 0
ESTADISTICAS_RBO_OFFSET EQU 1
ESTADISTICAS_KSC_OFFSET EQU 2
ESTADISTICAS_KDT_OFFSET EQU 3
ESTADISTICAS_ESTADO0_OFFSET EQU 4
ESTADISTICAS_ESTADO1_OFFSET EQU 5
ESTADISTICAS_ESTADO2_OFFSET EQU 6
ESTADISTICAS_SIZE EQU 7

;segmentacion_t* segmentar_casos(caso_t* arreglo_casos, int largo)
global segmentar_casos
segmentar_casos:
ret